#include "src/lws.h"
#define LWS_AMALGAMATION
#if LWS_MINIZ==1
#include "miniz/miniz.c"
#endif //LWS_MINIZ==1
#include "src/base64-decode.c"
#include "src/handshake.c"
#include "src/lws.c"
#include "src/service.c"
#include "src/pollfd.c"
#include "src/output.c"
#include "src/parsers.c"
#include "src/context.c"
#include "src/alloc.c"
#include "src/header.c"
#include "src/client.c"
#include "src/client-handshake.c"
#include "src/client-parser.c"
#include "src/sha-1.c"
#include "src/server.c"
#include "src/server-handshake.c"
#include "src/extension.c"
#include "src/extension-permessage-deflate.c"
#include "src/ranges.c"
#if LWS_WITH_SSL==1
#include "src/ssl.c"
#include "src/ssl-client.c"
#include "src/ssl-server.c"
#endif //LWS_WITH_SSL==1
#ifdef WIN32
#include "src/lws-plat-win.c"
#else // WIN32
#include "src/lws-plat-unix.c"
#endif //WIN32
